version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hubspot-lambda-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gmp3aj25z4qy"
s3_prefix = "hubspot-lambda-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
disable_rollback = true
